### ISSUE TITLE
No longer working from Oct 2022

### ISSUE THREAD

**Issue by giri256** [RDE3/Mac_Spotify_Adblock#12]

**Comment by ckapchi** [comment]
Blocked incoming connections for spotify on my firewall and it works for me.

**Comment by Syzygianinfern0** [comment]
> Blocked incoming connections for spotify on my firewall and it works for me.

Could you elaborate on how you did that?

**Comment by pyksoy** [comment]
it's not working for me either. After installing Spotify Adblock, I just can not open Spotify anymore. Need to reinstall it but then the Adblock becomes useless

**Comment by KieranK07** [comment]
Is this still a problem? Does this still work, and if not, is there an alternative?

**Comment by Syzygianinfern0** [comment]
I think this project is no longer maintained. I've been using this 👇 and it works really great! 
https://github.com/SpotX-CLI/SpotX-Mac

**Comment by KieranK07** [comment]
So far it's working for me too! Thanks so much for your help!

**Comment by RiotNrrrd** [comment]
The reason why Mac_Spotify_Adblock doesn't work with recent versions of Spotify is because Spotify changes the Chromium Framework and it calls various _cef_*_ functions in that Framework.  If you look at the _spotiblock.c_ source file, the author is basically creating stubs for all of the calls that are not in his replacement Framework to call back to the _.orig_-renamed Framework to run them from there.

There are about a dozen new calls that are not in his currently-distributed _spotiblock.c_ file.  I added them all in the appropriate places and now Spotify (Spotify for macOS Intel version 1.2.9.743.g85d9593d) comes up.

Try applying this (with _patch -p1_) _[spotiblock.c.patch](https://github.com/RDE3/Mac_Spotify_Adblock/files/11269239/spotiblock.c.patch)_

**Comment by Devanshu-17** [comment]
@giri256 @ckapchi @Syzygianinfern0 @pyksoy @KieranK07 @RiotNrrrd 

@jimmysofat6864 @ArtemisGraphic @HatshibaInu @Amiir97 @Syzygianinfern0 @lcaamal @deavy @Sawen1981 @RiotNrrrd

Hey guys. Sorry for not replying earlier. I was busy irl stuff. Yes, you all are correct that this repo is no longer being maintained. However, if you all want, you can contribute to this by opening a pull request.

**Comment by RiotNrrrd** [comment]
> _Hey guys. Sorry for not replying earlier. I was busy irl stuff. Yes, you all are correct that this repo is no longer being maintained. However, if you all want, you can contribute to this by opening a pull request._

I think everyone has gravitated to SpotX, which seems a lot more full-featured and does not require constant updates to a Chromium Framework stubs generator method like yours does.

**Comment by Devanshu-17** [comment]
> ###
> **[RiotNrrrd](/RiotNrrrd) ** commented [Apr 23, 2023](#issuecomment-1518924977)

That's wonderful. SpotX is a much more efficient method than this.
